### ISSUE TITLE
Issue when installing caused by sudo requiring password.

### ISSUE THREAD

**Issue by RudolfDG** [jsiebens/hashi-up#12]
`hashi-up nomad install \                                                                                       
  --ssh-target-addr $IP \
  --ssh-target-user ubuntu \
  --server
[INFO] Uploading generated Nomad configuration ...
[INFO] Installing Nomad ...
sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
error received during installation: Process exited with status 1
`
I've generated an ssh key and added it to authorized keys on the remote server, but it seems to not be working. I tried to use a passwordless ssh key, but that didn't make a difference.

**Comment by RudolfDG** [comment]
Fixed by temporarily disabling sudo asking for password by editing /etc/sudoers on the server.

**Comment by jsiebens** [comment]
Hi @RudolfDG 
Thanks for trying hashi-up and reporting this.
Your workaround will do the trick, but I'm willing to re-open this issue and try to add support for sudo password in hashi-up
