### ISSUE TITLE
Not running 'apt update' causing: "E: Unable to locate package unzip"

### ISSUE THREAD

**Issue by odinho** [jsiebens/hashi-up#14]
```
Flag --client has been deprecated, use the new flag client-addr
[INFO] Uploading generated Consul configuration ...
[INFO] Installing Consul ...
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package unzip
error received during installation: Process exited with status 100
```

Logging in on the server and running `apt update` first solves the issue. :)  (ah and also, the docs said to use `--client`, but I see it is now `--client-addr`.)

**Comment by jsiebens** [comment]
Hi @odinho
Apologies for the late reply ;-)

I considered adding this to the script, but most of the time this shouldn't be necessary and executing `apt update` every time can slow down the installation.
But if hashi-up can access the target host via ssh, the user can easily execute `apt update` remotely as well:
``` sh
ssh root@$TARGET_IP "apt update"
# or
ssh ubuntu@$TARGET_IP "sudo apt update"
```

**Comment by odinho** [comment]
Could maybe come with that suggestion/hint if you already are reading error messages. : )
