### ISSUE TITLE
cert create command is moved or broken

### ISSUE THREAD

**Issue by rgbrizzlehizzle** [jsiebens/hashi-up#16]
Womp, this does seem like an actual bug 

In the blog post I referred to in the other issue, there is a line to setup the certs

`hashi-up cert create --host 165.232.109.36 --host vault.example.com`

This functionality seems to have been moved or deleted

```
Error: unknown command "cert" for "hashi-up"
Run 'hashi-up --help' for usage.
unknown command "cert" for "hashi-up"
``` 

Browsed through the CLI manual a bit but didn't see anything explicitly cert related.

**Comment by posemon** [comment]
@rgbrizzlehizzle You must use
`hashi-up tls cert create ...`

instead of
`hashi-up cert create ...`

**Comment by jsiebens** [comment]
Hi @rgbrizzlehizzle,

You were right, the cert subcommand was incorrectly removed when releasing version 0.10.0.
The functionality is recovered in the latest release.
