### ISSUE TITLE
Allow the location of the `get` actions to be configurable

### ISSUE THREAD

**Issue by tylert** [jsiebens/hashi-up#17]
At the moment, `hashi-up <tool> get` fetches always into `~/bin/`.  It would be wonderful to be able to control where this binary gets stored.

Hashi-up is an extremely valuable tool for working with disposable build agents.  It is hoped that this feature will allow these build agents to be more "flexible".

**Comment by tylert** [comment]
@jsiebens

**Comment by jsiebens** [comment]
@tylert The `get` command has already a flag available to configure a target directory

```
jsiebens@orion:~$ hashi-up consul get --help
Download Consul on your local machine

Usage:
  hashi-up consul get [flags]

Flags:
  -d, --dest string      Target directory for the downloaded binary (default "/home/jsiebens/bin")
  -h, --help             help for get
  -v, --version string   Version of Consul to install
```

I agree it is lacking some documentation

**Comment by tylert** [comment]
Thanks for pointing out my error.  I guess I missed going deeper into the help.  Very nice.
