### ISSUE TITLE
Unable to fetch newest version of terraform listed at releases.hashicorp.com

### ISSUE THREAD

**Issue by tylert** [jsiebens/hashi-up#19]
Using `get` causes hashi-up to automatically fetch the 0.15.3 version of terraform but https://releases.hashicorp.com/index.json or https://releases.hashicorp.com/index.html lists 0.15.4 as the latest version.

Do I need to reinstall hashi-up whenever there are new versions listed on the HashiCorp site or there some other method by which the newest versions are discovered by hashi-up?

```
$ hashi-up version
Version: v0.10.1
Git Commit: ec7f7281fc3536c3206ac64394517fb6850e13a1
```

**Comment by tylert** [comment]
@jsiebens

**Comment by tylert** [comment]
Nevermind.  This new version was apparently just posted.  Running it again caused it to pull 0.15.4.

**Comment by jsiebens** [comment]
@tylert Thanks for reporting this. Fix will be available in next release.

In the meanwhile, you can work around this issue by using $(pwd) as the destination, e.g.

`hashi-up terraform get -d $(pwd)`
