### ISSUE TITLE
Cert Documentation

### ISSUE THREAD

**Issue by NegativeFeedback** [jsiebens/hashi-up#21]
is there any docs on using the secure by default options? setting up certs and what not? or any helpful nudges. I can write up my experiences once I get there!

**Comment by jsiebens** [comment]
Hi @NegativeFeedback 

On [learn.hashicorp.com](https://learn.hashicorp.com/), you can find a lot of docs on how to set up certs and other configuration to make everything secure.

E.g
- https://learn.hashicorp.com/tutorials/consul/tls-encryption-secure
- https://learn.hashicorp.com/tutorials/consul/gossip-encryption-secure?in=consul/security
- 
Once you got all the pieces together, you could use the hashi-up with either the cli flags or if something is not supported with the flags, you can use a custom configuration file.

E.g 
- https://github.com/jsiebens/hashi-up/blob/master/docs/consul.md#install-consul-with-an-existing-configuration-file
