### ISSUE TITLE
Support for air-gaped environments using proxy

### ISSUE THREAD

**Issue by jamesdube** [jsiebens/hashi-up#28]
I really love hashi-up and looking forward to using it in our test environment at work, however its air gaped without internet access. It would be nice if i can provide cli flags to hashi-up so that it download binaries via a proxy. I'm also willing to work on that myself to contribute to this awesome tool.

**Comment by jsiebens** [comment]
hi @jamesdube
There is already a `--package` flag available which can be used to upload an already downloaded distribution package to your target host.
E.g. `hashi-up nomad install --ssh-target-addr $IP --package nomad_1.1.6_linux_amd64.zip --server`
That was added to support air-gapped installations, would that work for you?

**Comment by jamesdube** [comment]
Thanks @jsiebens , will have a look at that and come back to you shortly

**Comment by jamesdube** [comment]
Worked like a charm,

Thanks again!
