### ISSUE TITLE
3-node HA possible?

### ISSUE THREAD

**Issue by veyalla** [jsiebens/hashi-up#3]
Great effort, thank you for this!

This is more of a question - is there a way to have 3 nodes in a HA config, with each node performing both server and agent duties? If yes, how would one set it up using `hashi-up`?

**Comment by jsiebens** [comment]
Hi @veyalla 

Yes indeed, Nomad can be started in both server and client mode, although it might not be the recommended way to build a Nomad cluster.
With `hashi-up` you just have to add both the `--server` and the `--client` flags when provisioning the server nodes, e.g:

```
export SERVER_1_IP=192.168.0.100
export SERVER_2_IP=192.168.0.101
export SERVER_3_IP=192.168.0.102

hashi-up nomad install --ip $SERVER_1_IP --server --client --bootstrap-expect 3 --retry-join $SERVER_1_IP --retry-join $SERVER_2_IP --retry-join $SERVER_3_IP
hashi-up nomad install --ip $SERVER_2_IP --server --client --bootstrap-expect 3 --retry-join $SERVER_1_IP --retry-join $SERVER_2_IP --retry-join $SERVER_3_IP
hashi-up nomad install --ip $SERVER_3_IP --server --client --bootstrap-expect 3 --retry-join $SERVER_1_IP --retry-join $SERVER_2_IP --retry-join $SERVER_3_IP
```

**Comment by veyalla** [comment]
Thank you, keep up the great project!
