### ISSUE TITLE
Cert Command Error

### ISSUE THREAD

**Issue by nickpoulos** [jsiebens/hashi-up#30]
Great little tool thanks for creating. 

I am tryin to follow along with this tutorial, which generates a certificate for Vault automatically with hashi-up? But I get an error when trying to run the `cert` command. 

https://johansiebens.dev/posts/2020/12/installing-hashicorp-vault-on-digitalocean-with-hashi-up/

**Comment by jsiebens** [comment]
hi @nickpoulos 

The blog post should be updated, the command is now `hashi-up tls create cert`

**Comment by nickpoulos** [comment]
Wow, thank you for quick response and action here.  

I actually am writing a little post on Medium doing a walkthrough of setting up an automated HashiCorp cluster (VPC, Consul, Nomad, Vault) on Digital Ocean using Terraform and Hashi-Up. 

I will shoot you a link later this week when it's all done!
