### ISSUE TITLE
terraform outputs in digitalocean/install_boundary.sh example cause host not found error

### ISSUE THREAD

**Issue by ruffCode** [jsiebens/hashi-up#34]
I recently discovered this great tool and ran into some trouble running the boundary_install script for digital ocean.

It seems that unless you pass the "-r" flag to the terraform IP address outputs the connection fails.

I don't enough about Go to make any educated guesses. I guess it could also be a shell issue, I am using ZSH on Ubuntu 22.04 for reference.

Thanks and great work!

-Alexi

**Comment by jsiebens** [comment]
That is more a Terraform version issue I guess.
I've updated the examples with the -raw flag, now it should be ok
