### ISSUE TITLE
Is it possible to have both agent at server on the same hardware

### ISSUE THREAD

**Issue by Squazz** [jsiebens/hashi-up#44]
I know it's strongly advised against.
But for small setups, and when you don't have a lot of hardware, it could be fine for a home-lab situation. 
Having two or three raspberry pis, and have them all run servers and agents would enable for a little load balancing and redundancy.

In that scenario, having 1 server and two agents, is rather vulnerable.

**Comment by jsiebens** [comment]
Hi @Squazz ,

With hashi-up you can install an Nomad as a client and as a server on a single host.
But I think your question is more of a general Nomad deployment topology question and not really related to hashi-up, no?
Perhaps [HashiCorp Discuss](https://discuss.hashicorp.com/c/nomad/28) is a better place to ask such questions.

**Comment by Squazz** [comment]
Oh, I see now :) 

I just tried installing consul server and client on the same node, and that did not work. Assumed then that Nomad as both server and client wouldn't work either
