### ISSUE TITLE
Error on nomad install on RASPI 4 with Ubuntu 20.04

### ISSUE THREAD

**Issue by bigwasp** [jsiebens/hashi-up#5]
**I tried to install nomad with hashi-up as documented**

export IP=192.168.0.31
hashi-up nomad install --ssh-target-addr $IP --ssh-target-user ubuntu --server

**I got following output:**
Uploading Nomad configuration and certificates...
Installing Nomad...
[INFO]  Downloading and unpacking nomad_1.0_linux_arm64.zip
Error: error received during installation: Process exited with status 22

The consul installation worked without any issue

regards bigwasp

**Comment by bigwasp** [comment]
It seems the installer tries to download the wrong file.
It will fetch nomad_1.0_linux_arm64.zip but looking at https://www.nomadproject.io/downloads
it is named nomad_1.0.0_linux_arm64.zip

Trying to fetch nomad_1.0_linux_arm64.zip gives me an ERROR 403: Forbidden

**Comment by bigwasp** [comment]
looking on the sourcecode pointed me in the right direction
**command.Flags().StringVar(&version, "version", "", "Version of Nomad to install, default to latest available")**

adding version saved my day

hashi-up nomad install --ssh-target-addr $IP --ssh-target-user ubuntu -**-version 1.0.0** --server

**Comment by jsiebens** [comment]
Thanks for reporting this.

hashi-up is using https://checkpoint.hashicorp.com/ to get the latest version of the products. 
Since the 1.0 release of Nomad, this service is returning 1.0 as value, instead of 1.0.0.

For now, adding the `--version` flag is a good workaround.
